# Generated by Django 3.2.6 on 2022-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
