# Generated by Django 3.2.6 on 2022-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220206_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='category',
            field=models.CharField(choices=[('El', 'Electronics'), ('H', 'Home'), ('F', 'Fashion'), ('T', 'Toys')], max_length=30),
        ),
    ]
