# Generated by Django 3.2.6 on 2022-02-06 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_createlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='category',
            field=models.CharField(choices=[('E', 'Electronics'), ('H', 'Home'), ('F', 'Fashion'), ('T', 'Toys')], max_length=30),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
