# Generated by Django 3.2.6 on 2022-02-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_watchlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys')], max_length=30),
        ),
    ]
